## provide the name of the namespace
namespace:
  name: staging

## set the number of replicas for an application 
replicaCount: 1

## define the image to execute with the Deployment 
image:
  repository: nginx
  tag: 1.18.0

resources:
  cpu: 50m
  memory: 128Mi

configMap:
  data:
    "version: 1.18.0"