## provide the name of the namespace
namespace:
  name: demo

## set the number of replicas for an application 
replicaCount: 3

## define the image to execute with the Deployment 
image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

resources:
  cpu: 50m
  memory: 256Mi

service:
  port: 8111
  type: ClusterIP

configMap:
  data:
    "version: alpine"

## 